### ISSUE TITLE
[REQ] Screenshots in action?

### ISSUE THREAD

**Issue by apollolux** [Eggbertx/QtSphere-IDE#1]
Hey dude, saw you were working on this! I'd like to know what functionality would be needed for the app to be in an acceptable enough state to make screenshots of it in action similar to how the other editors did.

**Comment by Eggbertx** [comment]
Right now, code editing is the only thing that really "works", but that isn't very interesting. I'm currently working on an image editor widget that can then be used for editing images, sprites, and tiles. Then I'm going to work on rendering maps.

**Comment by Eggbertx** [comment]
An update: I'm ditching code editing to focus on Sphere-specific formats, so I'll put up a screenshot as soon as there's something relevant to look at.
